---
name: "build-configurator-server"
github: "jenkinsci/build-configurator-plugin"
paths:
  - "com/amcbridge/build-configurator-server"
developers:
  - ldap: "amcbridgedevteam"
  - github: "AMCBridgeDevTeam"
  - github: "roman-bilyi"
repository_team: "build-configurator-plugin Developers"
