---
name: "parent"
github: "jenkinsci/configuration-as-code-plugin"
paths:
  - "io/jenkins/configuration-as-code/parent"
developers:
  - "praqma"
  - "jetersen"
  - "oleg_nenashev"
  - "timja"
cd:
  enabled: true
  exclusive: true
security:
  contacts:
    jira: "jetersen"
