---
name: "configurationslicing"
github: &gh "jenkinsci/configurationslicing-plugin"
cd:
    enabled: true
issues:
  - jira: '15597'  # configurationslicing-plugin
  - github: *gh
paths:
  - "org/jenkins-ci/plugins/configurationslicing"
  - "org/jvnet/hudson/plugins/configurationslicing"
developers:
  - ldap: "mdonohue"
  - ldap: "ninian"
    github: "ninian"
  - ldap: "guysoft"
    github: "guysoft"
  - github: "gounthar"
  - github: "MarkEWaite"
  - github: "jacobrobertson"
  - github: "mgaunin"
  - github: "jmMeessen"
repository_team: "configurationslicing-plugin Developers"
