---
name: "tm4j-automation"
github: "jenkinsci/tm4j-automation-plugin"
issues:
  - jira: '24421'  # tm4j-automation-plugin
paths:
  - "com/adaptavist/tm4j-automation"
developers:
  - ldap: "vpelizza"
  - github: "otaviomedeiros"
  - github: "pelizza"
  - github: "chicofaccin"
repository_team: "tm4j-automation-plugin Developers"
