---
name: "google-analyze-code-security"
github: &GH "jenkinsci/google-analyze-code-security-plugin"
paths:
  - "io/jenkins/plugins/google-analyze-code-security"
developers:
  - ldap: "sanyam803"
    github: "sanyam803"
  - ldap: "adishagarwal"
issues:
  - jira: 29324
cd:
    enabled: true
repository_team: "google-analyze-code-security-plugin Developers"
