---
name: "permissive-script-security"
github: "jenkinsci/permissive-script-security-plugin"
issues:
  - jira: '21467'  # permissive-script-security-plugin
paths:
  - "org/jenkins-ci/plugins/permissive-script-security"
developers:
  - ldap: "olivergondza"
    github: "olivergondza"
repository_team: "permissive-script-security-plugin Developers"
