---
name: "configuration-as-code-groovy"
github: "jenkinsci/configuration-as-code-groovy-plugin"
issues:
  - jira: '24922'  # configuration-as-code-groovy-plugin
paths:
  - "io/jenkins/plugins/configuration-as-code-groovy"
developers:
  - ldap: "szandala"
    github: "szandala"
  - ldap: "jetersen"
    github: "jetersen"
repository_team: "configuration-as-code-groovy-plugin Developers"
additional_github_teams:
  - team: "jcasc-compatibility-reviewers"
    role: "Read"
