---
name: "configuration-as-code-secret-ssm"
github: "jenkinsci/configuration-as-code-secret-ssm-plugin"
issues:
  - jira: '24643'  # configuration-as-code-secret-ssm-plugin
paths:
  - "com/bambora/jenkins/plugin/casc/secrets/ssm/configuration-as-code-secret-ssm"
developers:
  - ldap: "patbos"
repository_team: "configuration-as-code-secret-ssm-plugin Developers"
additional_github_teams:
  - team: "jcasc-compatibility-reviewers"
    role: "Read"
