---
name: "extended-security-settings"
github: "jenkinsci/extended-security-settings-plugin"
issues:
  - jira: '24621'  # extended-security-settings-plugin
paths:
  - "io/jenkins/plugins/extended-security-settings"
developers:
  - ldap: "jvz"
    github: "jvz"
  - ldap: "wfollonier"
  - github: "Wadeck"
repository_team: "extended-security-settings-plugin Developers"
