---
name: "aws-global-configuration"
github: "jenkinsci/aws-global-configuration-plugin"
paths:
- "io/jenkins/plugins/aws-global-configuration"
developers:
- "jglick"
- "csanchez"
- "oleg_nenashev"
- "ifernandezcalvo"
