---
name: "config-driven-pipeline"
github: &gh "jenkinsci/config-driven-pipeline-plugin"
issues:
  - github: *gh
  - jira: '25129'  # config-driven-pipeline-plugin
paths:
  - "org/jenkins-ci/plugins/config-driven-pipeline"
developers:
  - ldap: "justinharringa"
    github: "justinharringa"
repository_team: "config-driven-pipeline-plugin Developers"
