---
name: "config-rotator"
github: "jenkinsci/config-rotator-plugin"
issues:
  - jira: '16536'  # config-rotator-plugin
paths:
  - "net/praqma/config-rotator"
developers:
  - ldap: "madsnielsen"
  - ldap: "praqma"
  - github: "wolfgarnet"
  - github: "ReleasePraqma"
  - github: "MadsNielsen"
  - github: "buep"
repository_team: "config-rotator-plugin Developers"
