---
name: "configure-job-column-plugin"
github: &gh "jenkinsci/configure-job-column-plugin"
issues:
  - github: *gh
paths:
  - "org/jenkins-ci/plugins/configure-job-column-plugin"
developers:
  - "notmyfault"
cd:
  enabled: true
