---
name: "docker-custom-build-environment"
github: "jenkinsci/docker-custom-build-environment-plugin"
issues:
  - jira: '20634'  # docker-custom-build-environment-plugin
paths:
  - "com/cloudbees/jenkins/plugins/docker-custom-build-environment"
developers:
  - ldap: "vlatombe"
  - ldap: "jonhermansen"
    github: "jonhermansen"
repository_team: "docker-custom-build-environment-plugin Developers"
