---
name: "ibm-application-security"
github: "jenkinsci/appscan-plugin"
paths:
  - "com/ibm/ibm-application-security"
  - "com/hcl/security/ibm-application-security"
developers:
  - ldap: "mattmurp"
additional_github_teams:
  - team: "ibm-asoc-plugin Developers"
    role: "Admin"
