---
name: "probely-security"
github: "jenkinsci/probely-security-plugin"
issues:
  - jira: '24923'  # probely-security-plugin
paths:
  - "io/jenkins/plugins/probely-security"
developers:
  - ldap: "poupas"
    github: "poupas"
  - github: "bbarao"
  - github: "tmendo"
  - github: "hcastilho"
repository_team: "probely-security-plugin Developers"
