---
name: "provar-automation"
github: &GH "jenkinsci/provar-automation-plugin"
paths:
  - "io/jenkins/plugins/provar-automation"
developers:
  - ldap: "mrdailey99"
    github: "mrdailey99"
issues:
  - github: *GH
cd:
    enabled: true
repository_team: "provar-automation-plugin Developers"
