---
name: "configuration-as-code-secret-ssm"
github: "jenkinsci/configuration-as-code-secret-ssm-plugin"
paths:
- "com/bambora/jenkins/plugin/casc/secrets/ssm/configuration-as-code-secret-ssm"
developers:
- "patbos"
