---
name: "scm-sync-configuration"
github: "jenkinsci/scm-sync-configuration-plugin"
paths:
- "org/jenkins-ci/plugins/scm-sync-configuration"
- "org/jvnet/hudson/plugins/scm-sync-configuration"
developers:
- "fcamblor"
- "ndeloof"
- "rodrigc"
- "palacgui"
