---
name: "compuware-common-configuration"
github: "jenkinsci/compuware-common-configuration-plugin"
issues:
  - jira: '23140'  # compuware-common-configuration-plugin
paths:
  # New releases blocked due to non-free license, see 2023-03-20 project meeting
  - "com/compuware/jenkins/compuware-common-configuration-releaseblock"
developers:
  - "cpwr_jenkins"
