---
name: "read-only-configurations"
github: "jenkinsci/read-only-configurations-plugin"
issues:
  - jira: '16820'  # read-only-configurations-plugin
paths:
  - "org/jenkins-ci/plugins/read-only-configurations"
developers:
  - ldap: "lvotypkova"
repository_team: "read-only-configurations-plugin Developers"
additional_github_teams:
  - team: "computer-queue-plugin Developers"
    role: "Admin"
