---
name: "qualys-api-security"
github: "jenkinsci/qualys-api-security-plugin"
issues:
  - jira: '26123'  # qualys-api-security-plugin
paths:
  - "com/qualys/plugins/qualys-api-security"
developers:
  - ldap: "qualys"
  - github: "pmgupte"
  - github: "nikita-bedmutha"
  - github: "gwaghmare"
  - github: "qualys-plugins"
  - github: "aphatangade"
repository_team: "qualys-api-security-plugin Developers"
additional_github_teams:
  - team: "qualys Developers"
    role: "Admin"
