---
name: "secone-security"
github: &GH "jenkinsci/secone-security-plugin"
paths:
  - "io/jenkins/plugins/secone-security"
developers:
  - ldap: "rahuldarekar"
  - ldap: "saurabhthatte_sec1"
  - github: "saurabhthatte007"
  - github: "rahuldarekar222"
issues:
  - jira: 29323
cd:
    enabled: true
repository_team: "secone-security-plugin Developers"
