---
name: "contrast-continuous-application-security"
github: "jenkinsci/contrast-continuous-application-security-plugin"
paths:
- "org/jenkins-ci/plugins/contrast-continuous-application-security"
developers:
- "gsmoore"
- "sergii_contrast"