---
name: "prometheus"
github: &gh "jenkinsci/prometheus-plugin"
issues:
  - github: *gh
  - jira: '21450'  # prometheus-plugin
paths:
  - "org/jenkins-ci/plugins/prometheus"
developers:
  - ldap: "waschndolos"
  - github: "lsjostro"
  - github: "Waschndolos"
cd:
    enabled: true
repository_team: "prometheus-plugin Developers"
