---
name: "beagle-security"
github: "jenkinsci/beagle-security-plugin"
issues:
  - jira: '25629'  # beagle-security-plugin
paths:
  - "io/jenkins/plugins/beagle-security"
developers:
  - ldap: "rejah"
  - github: "rejahrehim"
repository_team: "beagle-security-plugin Developers"
