---
name: "environment-variable-page-decoration"
github: "jenkinsci/environment-variable-page-decoration-plugin"
issues:
  - jira: '23229'  # environment-variable-page-decoration-plugin
paths:
  - "org/jenkins-ci/plugins/environment-variable-page-decoration"
developers:
  - ldap: "tvon"
    github: "tvon"
repository_team: "environment-variable-page-decoration-plugin Developers"
