---
name: "build-environment"
github: "jenkinsci/build-environment-plugin"
issues:
  - jira: '17667'  # build-environment-plugin
paths:
  - "org/jenkins-ci/plugins/build-environment"
developers:
  - "stefanbrausch"
