---
name: "xpath-config-viewer"
github: "jenkinsci/xpath-config-viewer-plugin"
issues:
  - jira: '17546'  # xpath-config-viewer-plugin
paths:
  - "org/jenkins-ci/plugins/xpath-config-viewer"
developers:
  - github: "ffromm"
repository_team: "xpath-config-viewer-plugin Developers"
