---
name: "pom2config"
github: "jenkinsci/pom2config-plugin"
issues:
  - jira: '18220'  # pom2config-plugin
paths:
  - "org/jenkins-ci/plugins/pom2config"
developers: []
additional_github_teams:
  - team: "logfilesizechecker-plugin Developers"
    role: "Admin"
