---
name: "scm-sync-configuration"
github: &gh "jenkinsci/scm-sync-configuration-plugin"
issues:
  - jira: '15757'  # scm-sync-configuration-plugin
  - github: *gh
paths:
  - "org/jenkins-ci/plugins/scm-sync-configuration"
  - "org/jvnet/hudson/plugins/scm-sync-configuration"
developers:
  - ldap: "rodrigc"
  - ldap: "palacgui"
  - github: "guipal"
repository_team: "scm-sync-configuration-plugin Developers"
