---
name: "pipeline-config-history"
github: &gh "jenkinsci/pipeline-config-history-plugin"
issues:
  - github: *gh
paths:
  - "org/jenkins-ci/plugins/pipeline-config-history"
developers:
  - ldap: "jochenafuerbacher"
  - ldap: "robinschulz"
  - ldap: "stefanbrausch"
    github: "stefanbrausch"
  - github: "Jochen-A-Fuerbacher"
  - github: "RobinRSchulz"
repository_team: "pipeline-config-history-plugin Developers"
