---
name: "lambdatest-automation"
github: "jenkinsci/lambdatest-automation-plugin"
issues:
  - jira: '24652'  # lambdatest-automation-plugin
paths:
  - "org/jenkins-ci/plugins/lambdatest-automation"
developers:
  - ldap: "lambdatest"
  - github: "psych0der"
  - github: "sushobhit-lt"
repository_team: "lambdatest-automation-plugin Developers"
