---
name: "aws-global-configuration"
github: &gh "jenkinsci/aws-global-configuration-plugin"
issues:
  - github: *gh
paths:
  - "io/jenkins/plugins/aws-global-configuration"
cd:
  enabled: true
developers:
  - "jglick"
  - "csanchez"
  - "oleg_nenashev"
  - "timja"
  - "@cloudbees-developers"
security:
  contacts:
    jira: "cloudbees_security_members"
