---
name: "configure-job-column-plugin"
github: &gh "jenkinsci/configure-job-column-plugin"
issues:
  - github: *gh
paths:
  - "org/jenkins-ci/plugins/configure-job-column-plugin"
developers:
  - ldap: "notmyfault"
  - github: "NotMyFault"
cd:
    enabled: true
repository_team: "configure-job-column-plugin Developers"
