---
name: "config-driven-pipeline"
github: &gh "jenkinsci/config-driven-pipeline-plugin"
issues:
- github: *gh
- jira: '25129' # config-driven-pipeline-plugin
paths:
- "org/jenkins-ci/plugins/config-driven-pipeline"
developers:
- "justinharringa"
