---
name: "multi-slave-config-plugin"
github: "jenkinsci/multi-slave-config-plugin"
issues:
  - jira: '15928'  # multi-slave-config-plugin
paths:
  - "com/sonyericsson/hudson/plugins/multi-slave-config-plugin/multi-slave-config-plugin"
developers:
  - ldap: "rsandell"
  - github: "fredrikpersson"
  - github: "orjanpercy"
repository_team: "multi-slave-config-plugin Developers"
