---
name: "environment-filter-utils"
github: &GH "jenkinsci/environment-filter-utils-plugin"
issues:
  - github: *GH
paths:
  - "io/jenkins/plugins/environment-filter-utils"
developers:
  - "@security"
cd:
  enabled: true
communityPluginMaintainers: false
