---
name: "environment-labels-setter"
github: "jenkinsci/environment-labels-setter-plugin"
paths:
  - "org/jenkins-ci/plugins/environment-labels-setter"
developers:
  - ldap: "olivergondza"
additional_github_teams:
  - team: "mail-watcher-plugin Developers"
    role: "Admin"
